name: Build and Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make libcurl4-openssl-dev libjson-c-dev libncurses-dev
    
    - name: Build project
      run: |
        make rebuild
        
    - name: Create package
      run: |
        mkdir -p dist
        cp anime-cli dist/
        cp README.md LICENSE dist/
        cd dist
        tar -czvf ../anime-cli.tar.gz *
    
    - name: Generate version
      id: version
      run: echo "version=$(date +'%Y.%m.%d')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
    - name: Create Release and Upload Asset
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        VERSION=${{ steps.version.outputs.version }}
        RELEASE_NOTES="Automated build from commit ${{ github.sha }}\n\n**Changes in this release:**\n${{ github.event.head_commit.message }}"
        
        # Create release using GitHub CLI
        gh release create "v$VERSION" \
          --title "Release $VERSION" \
          --notes "$RELEASE_NOTES" \
          "./anime-cli.tar.gz#anime-cli-$VERSION.tar.gz"
