name: Build and Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make libcurl4-openssl-dev libjson-c-dev libncurses-dev
    
    - name: Build project
      run: |
        make rebuild
        
    - name: Create package
      run: |
        mkdir -p dist
        cp anime-cli.exe dist/anime-cli
        cp README.md LICENSE dist/
        cd dist
        tar -czvf ../anime-cli.tar.gz *
    
    - name: Generate version
      id: version
      run: echo "version=$(date +'%Y.%m.%d')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.version }}
        release_name: Release ${{ steps.version.outputs.version }}
        draft: false
        prerelease: false
        body: |
          Automated build from commit ${{ github.sha }}
          
          **Changes in this release:**
          ${{ github.event.head_commit.message }}
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./anime-cli.tar.gz
        asset_name: anime-cli-${{ steps.version.outputs.version }}.tar.gz
        asset_content_type: application/gzip
